---
- hosts: all
  tasks:

  - name: Copy service files to a remote server
    copy:
      src: systemd/
      dest: /etc/systemd/system/

  - name: enable services
    systemd:
      name: treetracker-token-api
      enabled: true

#  - name: enable services
#    systemd:
#      name: notify-sentry@service
#      enabled: true

  - name: daemon reload
    systemd:
      daemon-reload: true


